/* Generated By:JavaCC: Do not edit this line. valdtingConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface valdtingConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ADD = 1;
  /** RegularExpression Id. */
  int AND = 2;
  /** RegularExpression Id. */
  int WITH = 3;
  /** RegularExpression Id. */
  int SOURCE = 4;
  /** RegularExpression Id. */
  int TEXT = 5;
  /** RegularExpression Id. */
  int SPACE = 6;
  /** RegularExpression Id. */
  int FONT = 7;
  /** RegularExpression Id. */
  int COLOR = 8;
  /** RegularExpression Id. */
  int IMAGE = 9;
  /** RegularExpression Id. */
  int HEADING = 10;
  /** RegularExpression Id. */
  int LINK = 11;
  /** RegularExpression Id. */
  int space = 12;
  /** RegularExpression Id. */
  int PARAGRAPH = 13;
  /** RegularExpression Id. */
  int para = 14;
  /** RegularExpression Id. */
  int header = 15;
  /** RegularExpression Id. */
  int url = 16;
  /** RegularExpression Id. */
  int img = 17;
  /** RegularExpression Id. */
  int color = 18;
  /** RegularExpression Id. */
  int font = 19;
  /** RegularExpression Id. */
  int text = 20;
  /** RegularExpression Id. */
  int link = 21;
  /** RegularExpression Id. */
  int element = 22;
  /** RegularExpression Id. */
  int create = 23;
  /** RegularExpression Id. */
  int quote = 24;
  /** RegularExpression Id. */
  int sentence = 25;
  /** RegularExpression Id. */
  int DTEXT = 26;
  /** RegularExpression Id. */
  int ALPHANUMERIC = 27;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"ADD\"",
    "\"AND\"",
    "\"WITH\"",
    "\"SOURCE\"",
    "\"TEXT\"",
    "\" \"",
    "\"FONT\"",
    "\"COLOR\"",
    "\"IMAGE\"",
    "\"HEADING\"",
    "\"LINK\"",
    "<space>",
    "\"PARAGRAPH\"",
    "<para>",
    "<header>",
    "<url>",
    "<img>",
    "<color>",
    "<font>",
    "<text>",
    "<link>",
    "<element>",
    "<create>",
    "\"\\\"\"",
    "<sentence>",
    "<DTEXT>",
    "<ALPHANUMERIC>",
    "\"\\n\"",
    "\"\\t\"",
    "\"\\r\"",
  };

}
